create table public.books (
  id smallint generated by default as identity not null,
  name text not null,
  author text,
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),

  constraint books_pkey primary key (id)
);



create table public.book_sections (
  id integer generated by default as identity not null,
  book_id smallint not null,
  path_code text,
  quote_id integer not null,

  constraint pk_book_sections primary key (id),
  constraint uq_section_path unique (book_id, path_code),
  constraint fk_section_book foreign key (book_id) references public.books (id) on delete cascade
  constraint fk_section_quote foreign key (quote_id) references quotes (id) on delete cascade
);



create table public.quotes (
  id integer generated by default as identity not null,
  text text not null,
  meaning text not null,

  constraint pk_quotes primary key (id),
);




create table public.favorites (
  id uuid not null,
  quote_id integer not null,

  constraint pk_favorites primary key (id, quote_id),
  constraint fk_fav_user foreign key (id) references auth.users (id) on delete cascade,
  constraint fk_fav_quote foreign key (quote_id) references public.quotes (id) on delete cascade
);
